export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_URL = 'CHANGE_URL';
export const CHANGE_NOTE = 'CHANGE_NOTE';
export const SELECT_LEARNLINK = 'SELECT_LEARNLINK';
export const ADD_LEARNLINK = 'ADD_LEARNLINK';
